import 'package:flutter/material.dart';

class ColorSchemes{

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff48672f),
      surfaceTint: Color(0xff48672f),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffc9eea7),
      onPrimaryContainer: Color(0xff0c2000),
      secondary: Color(0xff56624b),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffdae7c9),
      onSecondaryContainer: Color(0xff141e0c),
      tertiary: Color(0xff386665),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffbbecea),
      onTertiaryContainer: Color(0xff00201f),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xfff9faef),
      onSurface: Color(0xff1a1d16),
      onSurfaceVariant: Color(0xff44483e),
      outline: Color(0xff74796d),
      outlineVariant: Color(0xffc4c8ba),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff2e312a),
      inversePrimary: Color(0xffadd18d),
      primaryFixed: Color(0xffc9eea7),
      onPrimaryFixed: Color(0xff0c2000),
      primaryFixedDim: Color(0xffadd18d),
      onPrimaryFixedVariant: Color(0xff314e19),
      secondaryFixed: Color(0xffdae7c9),
      onSecondaryFixed: Color(0xff141e0c),
      secondaryFixedDim: Color(0xffbecbae),
      onSecondaryFixedVariant: Color(0xff3f4a34),
      tertiaryFixed: Color(0xffbbecea),
      onTertiaryFixed: Color(0xff00201f),
      tertiaryFixedDim: Color(0xffa0cfce),
      onTertiaryFixedVariant: Color(0xff1e4e4d),
      surfaceDim: Color(0xffd9dbd0),
      surfaceBright: Color(0xfff9faef),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff3f5ea),
      surfaceContainer: Color(0xffedefe4),
      surfaceContainerHigh: Color(0xffe7e9de),
      surfaceContainerHighest: Color(0xffe2e3d9),
    );
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffadd18d),
      surfaceTint: Color(0xffadd18d),
      onPrimary: Color(0xff1b3704),
      primaryContainer: Color(0xff314e19),
      onPrimaryContainer: Color(0xffc9eea7),
      secondary: Color(0xffbecbae),
      onSecondary: Color(0xff29341f),
      secondaryContainer: Color(0xff3f4a34),
      onSecondaryContainer: Color(0xffdae7c9),
      tertiary: Color(0xffa0cfce),
      onTertiary: Color(0xff003736),
      tertiaryContainer: Color(0xff1e4e4d),
      onTertiaryContainer: Color(0xffbbecea),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff11140e),
      onSurface: Color(0xffe2e3d9),
      onSurfaceVariant: Color(0xffc4c8ba),
      outline: Color(0xff8e9286),
      outlineVariant: Color(0xff44483e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe2e3d9),
      inversePrimary: Color(0xff48672f),
      primaryFixed: Color(0xffc9eea7),
      onPrimaryFixed: Color(0xff0c2000),
      primaryFixedDim: Color(0xffadd18d),
      onPrimaryFixedVariant: Color(0xff314e19),
      secondaryFixed: Color(0xffdae7c9),
      onSecondaryFixed: Color(0xff141e0c),
      secondaryFixedDim: Color(0xffbecbae),
      onSecondaryFixedVariant: Color(0xff3f4a34),
      tertiaryFixed: Color(0xffbbecea),
      onTertiaryFixed: Color(0xff00201f),
      tertiaryFixedDim: Color(0xffa0cfce),
      onTertiaryFixedVariant: Color(0xff1e4e4d),
      surfaceDim: Color(0xff11140e),
      surfaceBright: Color(0xff373a33),
      surfaceContainerLowest: Color(0xff0c0f09),
      surfaceContainerLow: Color(0xff1a1d16),
      surfaceContainer: Color(0xff1e211a),
      surfaceContainerHigh: Color(0xff282b24),
      surfaceContainerHighest: Color(0xff33362f),
    );
  }
}